// ignore_for_file: constant_identifier_names
///
/// Flutter icons FlashMailIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlashMailIcons
///      fonts:
///       - asset: fonts/FlashMailIcons.ttf

import "package:flutter/widgets.dart";

class FlashMailIcons {
  FlashMailIcons._();

  static const _kFontFam = "FlashMailIcons";
  static const String? _kFontPkg = null;

  static const IconData sign_out =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redirect =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bin =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
